---
- name: my test playbook
  hosts: all
  become: true
  tasks:
    - name: install
      yum:
        name: httpd
        state: present


    - name: service
      service:
        name: httpd
        state: started

